version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: github_api_laravel
    container_name: github_api_laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./github_back/:/var/www
      - ./github_back/storage:/var/www/storage
    networks:
      - app-network

  db:
    image: mysql
    container_name: github_api_laravel_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: test123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: github_api_laravel_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./github_back/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
